# Generated by Django 4.1.7 on 2023-03-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalyanmapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=10),
        ),
    ]
