# Generated by Django 4.1.7 on 2023-03-25 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kalyanmapp', '0002_alter_detail_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biodata',
            name='native',
        ),
    ]
