# Generated by Django 4.1.7 on 2023-03-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalyanmapp', '0003_remove_biodata_native'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10),
        ),
    ]
